version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "11:00"
  open-pull-requests-limit: 10
  reviewers:
  - mcclowes
  ignore:
  - dependency-name: "@storybook/react"
    versions:
    - 6.1.11
    - 6.1.15
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
  - dependency-name: urijs
    versions:
    - 1.19.5
  - dependency-name: react-screenshot-test
    versions:
    - 2.2.2
  - dependency-name: react-scripts
    versions:
    - 4.0.1
