# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

# @todo: add linting

version: 2.1
anchors:
  defaults: &defaults
    docker:
      - image: circleci/node:11-browsers
    working_directory: ~/repo
  restore_cache: &restore_cache # Download and cache dependencies
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies- # fallback to using the latest cache if no exact match is found
  save_cache: &save_cache
    save_cache:
      paths:
        - node_modules
      key: v1-dependencies-{{ checksum "package.json" }}
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - *save_cache
      - run: npm run build
  lint:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - *save_cache
      - run: npm run format
  test-unit:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run: npm install
      - *save_cache
      - run:
          name: Unit tests
          command: npm run test
  test-screenshot:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Set up Git LFS
          command: |
            sudo apt-get install -y git-lfs
            git lfs install
            git lfs pull
      - run:
          name: Install fonts
          command: |
            sudo apt-get install -y fonts-open-sans \
                                    fonts-cantarell
      - *restore_cache
      - run: npm install
      - *save_cache
      - run:
          name: Screenshot tests
          command: npm run test:screenshot-ci
      - store_artifacts:
          path: src/utils/testing/__screenshots__
          destination: snapshots
workflows:
  check:
    jobs:
      - build
      - lint
      - test-unit
      - test-screenshot
      # - docker-image
